require 'rails_helper'

RSpec.describe "Graphs", type: :request do
  describe "GET /graph" do
    before do
      CsvParser.new(csv).save_new_measurements
      get "/graph"
    end

    describe "without data" do
      let(:csv) { "" }

      it "renders SVG" do
        expect(response.body).to include("<svg")
      end

      describe "the SVG" do
        let(:xml) do
          Nokogiri::HTML.parse(response.body)
        end

        let(:text_element) { xml.at_xpath('//svg/text') }
        let(:text) { text_element.text }
        let(:text_attributes) { text_element.attributes }

        it "has an error message" do
          expect(text).to eq "\nNo data\n"
        end

        it "has the correct fill color" do
          expect(text_attributes["fill"].value).to eq(SvgBuilder::STROKE_COLOR)
        end

        it "has the correct x coordinate" do
          expect(text_attributes["x"].value).to eq("500")
        end

        it "has the correct y coordinate" do
          expect(text_attributes["y"].value).to eq("500")
        end

      end
    end

    describe "with data" do
      let(:csv) do
        [
          "Glucose Data,Generated on,04-29-2025 10:34 PM UTC,Generated by,Jeffrey Waltzer",
          "Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mg/dL,Scan Glucose mg/dL,Non-numeric Rapid-Acting Insulin,Rapid-Acting Insulin (units),Non-numeric Food,Carbohydrates (grams),Carbohydrates (servings),Non-numeric Long-Acting Insulin,Long-Acting Insulin (units),Notes,Strip Glucose mg/dL,Ketone mmol/L,Meal Insulin (units),Correction Insulin (units),User Change Insulin (units)",
          "FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,03-14-2025 09:52 PM,0,180,,,,,,,,,,,,,,\r",
          "FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,03-14-2025 09:57 PM,0,182,,,,,,,,,,,,,,",
          "FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,03-14-2025 10:02 PM,0,179,,,,,,,,,,,,,,",
          "FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 05:17 PM,6,,,,,,,,,,,,,,,",
          "FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 05:18 PM,6,,,,,,,,,,,,,,,",
          "FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 05:19 PM,6,,,,,,,,,,,,,,,"
        ].join("\r\n")
      end
      
      it "renders SVG" do
        expect(response.body).to include("<svg")
      end

      describe "the SVG" do
        let(:xml) do
          Nokogiri::HTML.parse(response.body)
        end

        let(:polyline) { xml.at_xpath('//svg/svg/polyline').attributes }

        it 'has a polyline d' do
          expect(polyline['points'].value).to eq "0,2 300,0 600,3"
        end
      end
    end
  end
end
