require 'rails_helper'

RSpec.describe GlucoseCsv, type: :model do

  let(:csv) do
    <<-CSV
        Glucose Data,Generated on,02-16-2025 03:27 PM UTC,Generated by,Jeffrey Waltzer
        Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mg/dL,Scan Glucose mg/dL,Non-numeric Rapid-Acting Insulin,Rapid-Acting Insulin (units),Non-numeric Food,Carbohydrates (grams),Carbohydrates (servings),Non-numeric Long-Acting Insulin,Long-Acting Insulin (units),Notes,Strip Glucose mg/dL,Ketone mmol/L,Meal Insulin (units),Correction Insulin (units),User Change Insulin (units)
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 03:56 PM,0,308,,,,,,,,,,,,,,
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:01 PM,0,308,,,,,,,,,,,,,,
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:06 PM,0,299,,,,,,,,,,,,,,
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:11 PM,0,295,,,,,,,,,,,,,,
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:16 PM,1,308,,,,,,,,,,,,,,
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:21 PM,0,302,,,,,,,,,,,,,,
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:26 PM,0,300,,,,,,,,,,,,,,
    CSV
  end

  let(:glucose_csv) do
    GlucoseCsv.create(csv:)
  end

  xit 'extracts glucose values' do
    rows = glucose_csv.glucose_measurements

    expect(rows).to eq(
     [
       [DateTime.strptime('02-14-2025 03:56 PM', '%m-%d-%Y %k:%M %p'), 308],
       [DateTime.strptime('02-14-2025 04:01 PM', '%m-%d-%Y %k:%M %p'), 308],
       [DateTime.strptime('02-14-2025 04:06 PM', '%m-%d-%Y %k:%M %p'), 299],
       [DateTime.strptime('02-14-2025 04:11 PM', '%m-%d-%Y %k:%M %p'), 295],
       [DateTime.strptime('02-14-2025 04:16 PM', '%m-%d-%Y %k:%M %p'), 308],
       [DateTime.strptime('02-14-2025 04:21 PM', '%m-%d-%Y %k:%M %p'), 302],
       [DateTime.strptime('02-14-2025 04:26 PM', '%m-%d-%Y %k:%M %p'), 300],
     ]
   )
  end

end
