RSpec.describe CsvParser do
  describe "#build_measurement" do
    let(:csv_data) do
      <<~CSV.chomp
        Glucose Data,Generated on,04-29-2025 10:34 PM UTC,Generated by,Jeffrey Waltzer
        Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mg/dL,Scan Glucose mg/dL,Non-numeric Rapid-Acting Insulin,Rapid-Acting Insulin (units),Non-numeric Food,Carbohydrates (grams),Carbohydrates (servings),Non-numeric Long-Acting Insulin,Long-Acting Insulin (units),Notes,Strip Glucose mg/dL,Ketone mmol/L,Meal Insulin (units),Correction Insulin (units),User Change Insulin (units)
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,03-14-2025 09:52 PM,0,180,,,,,,,,,,,,,,
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,03-14-2025 09:57 PM,0,182,,,,,,,,,,,,,,
      CSV
    end

    it "calls create for each record" do
      allow(GlucoseMeasurement).to receive(:create!)
      CsvParser.new(csv_data).build_measurements

      expect(GlucoseMeasurement).to have_received(:create!).twice
    end
  end
end
