# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

GlucoseCsv.create!(
  csv:
    <<~EOF
        Glucose Data,Generated on,02-16-2025 03:27 PM UTC,Generated by,Jeffrey Waltzer
    Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mg/dL,Scan Glucose mg/dL,Non-numeric Rapid-Acting Insulin,Rapid-Acting Insulin (units),Non-numeric Food,Carbohydrates (grams),Carbohydrates (servings),Non-numeric Long-Acting Insulin,Long-Acting Insulin (units),Notes,Strip Glucose mg/dL,Ketone mmol/L,Meal Insulin (units),Correction Insulin (units),User Change Insulin (units)
    FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 03:56 PM,0,308,,,,,,,,,,,,,,
    FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:01 PM,0,308,,,,,,,,,,,,,,
    FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:06 PM,0,299,,,,,,,,,,,,,,
    FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:11 PM,0,295,,,,,,,,,,,,,,
    FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:16 PM,1,308,,,,,,,,,,,,,,
    FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:21 PM,0,302,,,,,,,,,,,,,,
    FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,02-14-2025 04:26 PM,0,300,,,,,,,,,,,,,,
    EOF
)
