require 'rails_helper'

RSpec.describe CsvUploadsController, type: :controller do
  describe "#create" do
    let(:csv) do
      <<~CSV.chomp
        Glucose Data,Generated on,04-29-2025 10:34 PM UTC,Generated by,Jeffrey Waltzer
        Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mg/dL,Scan Glucose mg/dL,Non-numeric Rapid-Acting Insulin,Rapid-Acting Insulin (units),Non-numeric Food,Carbohydrates (grams),Carbohydrates (servings),Non-numeric Long-Acting Insulin,Long-Acting Insulin (units),Notes,Strip Glucose mg/dL,Ketone mmol/L,Meal Insulin (units),Correction Insulin (units),User Change Insulin (units)
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,03-14-2025 09:52 PM,0,180,,,,,,,,,,,,,,
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,03-14-2025 09:57 PM,0,182,,,,,,,,,,,,,,
        FreeStyle Libre 3,99628558-b199-48dc-8a24-9ad9268aad6a,03-14-2025 10:02 PM,0,179,,,,,,,,,,,,,,
      CSV
    end

    let(:uploaded_file) { fixture_file_upload('tmp/ferd.csv', 'text/csv') }

    before do
      File.write(Rails.root.join('tmp', 'ferd.csv'), csv)
    end

    it "creates the measurement points" do
      put :create, params: { csv: uploaded_file }

      expect(GlucoseMeasurement.count).to eq(3)
    end
  end
end
